[versions]
aws-sdk-jvm = "1.5.93"
aws-sdk-java = "2.39.5"
dotenv = "6.4.1"
koog = "0.5.3"
kotlin = "2.2.20"
ktor = "3.3.0"
logback = "1.5.20"

[libraries]
awssdk-auth-java = { module = "software.amazon.awssdk:auth", version.ref = "aws-sdk-java" }
bedrock-runtime-jvm = { module = "aws.sdk.kotlin:bedrockruntime-jvm", version.ref = "aws-sdk-jvm" }
bedrock-agentcore-jvm = { module = "aws.sdk.kotlin:bedrockagentcore-jvm", version.ref = "aws-sdk-jvm" }
dotenv-kotlin = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }